
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebForm.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cart
{

    public string cartNumber { get; set; }

    public string orderID { get; set; }

    public string itemID { get; set; }

    public string itemname { get; set; }

    public Nullable<int> pricePerItem { get; set; }

    public Nullable<int> quantity { get; set; }

    public Nullable<int> totalPrice { get; set; }

    public string resellerID { get; set; }

}

}
