//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderList
    {
        public string orderID { get; set; }
        public string resellerID { get; set; }
        public Nullable<System.DateTime> createdDay { get; set; }
        public string C_status { get; set; }
        public string paymentMethod { get; set; }
        public string C_address { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public string paymentStatus { get; set; }
    }
}
